services:
  redis:
    image: redis/redis-stack:latest
    container_name: streamlinai-redis
    ports:
      - "6379:6379"
      - "8001:8001" 
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--save 60 1000
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: streamlinai-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - PORT=5000
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: streamlinai-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_SOCKET_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  redis_data:
